timezone:    Europe/London
remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jemoji
  - jekyll-remote-theme # add this line to the plugins list if you already have one

## solarized variant (dark/light)
solarized:
  theme:     dark
